CREATE TABLE TYPEOFINDUSTRY (
TYPEOFINDUSTRYID INTEGER NOT NULL AUTO_INCREMENT,
TYPEOFINDUSTRYNAME VARCHAR(30),
PRIMARY KEY (TYPEOFINDUSTRYID));

CREATE TABLE CLIENT (
CLIENTID INTEGER NOT NULL AUTO_INCREMENT,
CLIENTEMAIL VARCHAR(30),
CLIENTPASSWORD VARCHAR(100),
CLIENTNAME VARCHAR(30),
USER_TYPE CHAR(1),
CLIENTROLE VARCHAR(30),
ADMINTITLE VARCHAR(30),
NORMALUSERWORKNUMBER VARCHAR(30),
PRIMARY KEY (CLIENTID));


CREATE TABLE CUSTOMER (
CUSTOMERID INTEGER NOT NULL AUTO_INCREMENT,
CUSTOMERNAME VARCHAR(30),
CUSTOMERPHONENUMBER VARCHAR(30),
CUSTOMEREMAIL VARCHAR(100),
CUSTOMERWEBSITE VARCHAR(100),
CUSTOMERDESCRIPTION VARCHAR(100),
NORMALUSER_CLIENTID INTEGER,
TYPEOFINDUSTRY_TYPEOFINDUSTRYID INTEGER,
STREET_NUMBER VARCHAR(30),
STREET_ADDRESS VARCHAR(100),
SUBURB VARCHAR(30),
POSTCODE VARCHAR(30),
STATE VARCHAR(30),
PRIMARY KEY (CUSTOMERID));

ALTER TABLE CUSTOMER ADD
CONSTRAINT FK1_CUSTOMER
FOREIGN KEY (NORMALUSER_CLIENTID)
REFERENCES CLIENT(CLIENTID)
ON DELETE CASCADE;

ALTER TABLE CUSTOMER ADD
CONSTRAINT FK2_CUSTOMER
FOREIGN KEY (TYPEOFINDUSTRY_TYPEOFINDUSTRYID)
REFERENCES TYPEOFINDUSTRY(TYPEOFINDUSTRYID)
ON DELETE CASCADE;


CREATE TABLE CUSTOMERCONTACT (
CUSTOMERCONTACTID INTEGER NOT NULL AUTO_INCREMENT,
CUSTOMERCONTACTNAME VARCHAR(30),
CUSTOMERCONTACTPHONENUMBER VARCHAR(30),
CUSTOMERCONTACTGENDER VARCHAR(30),
CUSTOMERCONTACTDOB DATE,
CUSTOMERCONTACTWORKYEARS DECIMAL(3,1),
CUSTOMER_CUSTOMERID INTEGER,
PRIMARY KEY (CUSTOMERCONTACTID));

ALTER TABLE CUSTOMERCONTACT ADD
CONSTRAINT FK2_CUSTOMERCONTACT
FOREIGN KEY (CUSTOMER_CUSTOMERID)
REFERENCES CUSTOMER(CUSTOMERID)
ON DELETE CASCADE;


INSERT INTO JAVAEE.CLIENT (CLIENTID, CLIENTNAME, CLIENTEMAIL, CLIENTPASSWORD, USER_TYPE, CLIENTROLE, ADMINTITLE, NORMALUSERWORKNUMBER) VALUES (1, 'admin1', 'admin1@email.com', 'f64561e04c3be9cea6271afcd2b324f4b8654ed1b011f4f15ff4436e0100d5a0', 'A', 'admin', 'director', null);
INSERT INTO JAVAEE.CLIENT (CLIENTID, CLIENTNAME, CLIENTEMAIL, CLIENTPASSWORD, USER_TYPE, CLIENTROLE, ADMINTITLE, NORMALUSERWORKNUMBER) VALUES (2, 'normaluser1', 'normaluser1@email.com', 'b6ae50adeba1f4010fd19b0f3bf7dc20f6522269e22cf6886bc85f911ed5ccc1', 'N', 'normalUser', null,'nu001');
INSERT INTO JAVAEE.TYPEOFINDUSTRY (TYPEOFINDUSTRYID, TYPEOFINDUSTRYNAME) VALUES (1, 'Bank');
INSERT INTO JAVAEE.TYPEOFINDUSTRY (TYPEOFINDUSTRYID, TYPEOFINDUSTRYNAME) VALUES (2, 'Building');
INSERT INTO JAVAEE.TYPEOFINDUSTRY (TYPEOFINDUSTRYID, TYPEOFINDUSTRYNAME) VALUES (3, 'Data Communication');
INSERT INTO JAVAEE.TYPEOFINDUSTRY (TYPEOFINDUSTRYID, TYPEOFINDUSTRYNAME) VALUES (4, 'Education');
INSERT INTO JAVAEE.TYPEOFINDUSTRY (TYPEOFINDUSTRYID, TYPEOFINDUSTRYNAME) VALUES (5, 'Farm');
INSERT INTO JAVAEE.TYPEOFINDUSTRY (TYPEOFINDUSTRYID, TYPEOFINDUSTRYNAME) VALUES (6, 'Health');
INSERT INTO JAVAEE.TYPEOFINDUSTRY (TYPEOFINDUSTRYID, TYPEOFINDUSTRYNAME) VALUES (7, 'Mining');
INSERT INTO JAVAEE.TYPEOFINDUSTRY (TYPEOFINDUSTRYID, TYPEOFINDUSTRYNAME) VALUES (8, 'Publishing');
INSERT INTO JAVAEE.CUSTOMER (CUSTOMERID, CUSTOMERNAME, CUSTOMERPHONENUMBER,CUSTOMEREMAIL, CUSTOMERWEBSITE, CUSTOMERDESCRIPTION, NORMALUSER_CLIENTID, TYPEOFINDUSTRY_TYPEOFINDUSTRYID, 
	STREET_NUMBER, STREET_ADDRESS, SUBURB, POSTCODE, STATE) VALUES (1, 'customer1', '0400111222', 'customer1@email.com', 'www.customer1.com', 'customer 1 is good', 2, 1, '1', 'Dandenong Road', 'Caulfield East', '3145', 'VIC');
INSERT INTO JAVAEE.CUSTOMER (CUSTOMERID, CUSTOMERNAME, CUSTOMERPHONENUMBER,CUSTOMEREMAIL, CUSTOMERWEBSITE, CUSTOMERDESCRIPTION, NORMALUSER_CLIENTID, TYPEOFINDUSTRY_TYPEOFINDUSTRYID, 
	STREET_NUMBER, STREET_ADDRESS, SUBURB, POSTCODE, STATE) VALUES (2, 'customer2', '0400111222', 'customer2@email.com', 'www.customer2.com', 'customer 2 is good', 2, 2, '2', 'Dandenong Road', 'Caulfield East', '3145', 'VIC');	
INSERT INTO JAVAEE.CUSTOMERCONTACT (CUSTOMERCONTACTID, CUSTOMERCONTACTNAME, CUSTOMERCONTACTPHONENUMBER, CUSTOMERCONTACTGENDER, CUSTOMERCONTACTDOB, CUSTOMERCONTACTWORKYEARS, CUSTOMER_CUSTOMERID) values
	(1, 'customerContactA', '0400111222', 'male', '1995-01-01', 1.5, 1);
INSERT INTO JAVAEE.CUSTOMERCONTACT (CUSTOMERCONTACTID, CUSTOMERCONTACTNAME, CUSTOMERCONTACTPHONENUMBER, CUSTOMERCONTACTGENDER, CUSTOMERCONTACTDOB, CUSTOMERCONTACTWORKYEARS, CUSTOMER_CUSTOMERID) values
	(2, 'customerContactB', '0400111222', 'female', '1995-01-01', 2.0, 2);


